import sys

if len(sys.argv) < 4:
    sys.stderr.write("Not enough arguments.")
    sys.exit(1)


def c_escape(x):
    return "{%s}" % (",".join(str(ord(xi)) for xi in x),)


with open(sys.argv[1], "rb") as fin:
    with open(sys.argv[3], "wb") as fout:
        dat = fin.read()
        tgt = sys.argv[2]
        # TODO: is it a good idea to duplicate variables this much?
        fout.write("// autogenerated\nchar %s_dat[] = " % tgt)
        fout.write(c_escape(dat))
        fout.write(";\nchar *%s = %s_dat;\nchar *%s_end = %s_dat + sizeof(%s_dat);\n" % (tgt, tgt, tgt, tgt, tgt))
        fout.write("_Static_assert(sizeof(%s_dat) == %d, \"internal mismatch (see incbin.py)\");\n" % (tgt, len(dat)))
